CREATE DATABASE FitnessApp;
GO

USE FitnessApp;
GO

-- Tabla USUARIO
CREATE TABLE USUARIO (
    USUARIOID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBREUSUARIO VARCHAR(50) NOT NULL,
    PASSWORDUSUARIO VARCHAR(50) NOT NULL,
    XP INT DEFAULT 0,
    NIVEL INT DEFAULT 1
);
GO

-- Tabla PEGATINA
CREATE TABLE PEGATINA (
    PEGATINA_ID INT IDENTITY(1,1) PRIMARY KEY,
    DESBLOQUEADO BIT DEFAULT 0
);
GO

-- Tabla POSEER (relación N:M entre USUARIO y PEGATINA)
CREATE TABLE POSEER (
    USUARIOID INT,
    PEGATINA_ID INT,
    PRIMARY KEY (USUARIOID, PEGATINA_ID),
    FOREIGN KEY (USUARIOID) REFERENCES USUARIO(USUARIOID),
    FOREIGN KEY (PEGATINA_ID) REFERENCES PEGATINA(PEGATINA_ID)
);
GO

-- Tabla RUTINA
CREATE TABLE RUTINA (
    ID_RUTINA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_RUTINA VARCHAR(50) NOT NULL
);
GO

-- Tabla CREAR (relación N:M entre USUARIO y RUTINA)
CREATE TABLE CREAR (
    USUARIOID INT,
    ID_RUTINA INT,
    PRIMARY KEY (USUARIOID, ID_RUTINA),
    FOREIGN KEY (USUARIOID) REFERENCES USUARIO(USUARIOID),
    FOREIGN KEY (ID_RUTINA) REFERENCES RUTINA(ID_RUTINA)
);
GO

-- Tabla DIA
CREATE TABLE DIA (
    ID_DIA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_DIA VARCHAR(50) NOT NULL
);
GO

-- Tabla EJERCICIO
CREATE TABLE EJERCICIO (
    ID_EJERCICIO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_EJERCICIO VARCHAR(50) NOT NULL,
    REPETICIONES_EJERCICIO INT,
    PESO_EJERCICIO FLOAT,
    SERIES_EJERCICIO INT
);
GO

-- Tabla ORGANIZAR (relación N:M entre RUTINA y DIA)
CREATE TABLE ORGANIZAR (
    ID_RUTINA INT,
    ID_DIA INT,
    PRIMARY KEY (ID_RUTINA, ID_DIA),
    FOREIGN KEY (ID_RUTINA) REFERENCES RUTINA(ID_RUTINA),
    FOREIGN KEY (ID_DIA) REFERENCES DIA(ID_DIA)
);
GO

-- Tabla INCLUIR (relación N:M entre DIA y EJERCICIO)
CREATE TABLE INCLUIR (
    ID_DIA INT,
    ID_EJERCICIO INT,
    PRIMARY KEY (ID_DIA, ID_EJERCICIO),
    FOREIGN KEY (ID_DIA) REFERENCES DIA(ID_DIA),
    FOREIGN KEY (ID_EJERCICIO) REFERENCES EJERCICIO(ID_EJERCICIO)
);
GO